# Generated by Django 4.0.3 on 2022-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=75, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('position', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
