# Generated by Django 4.0.3 on 2022-04-10 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
