# Generated by Django 4.0.3 on 2022-04-10 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_employee_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
