# Generated by Django 4.0.3 on 2022-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_employee_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
