# Generated by Django 4.0.3 on 2022-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_employee_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('urgency', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('updateId', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
