# Generated by Django 4.0.3 on 2022-04-10 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_ticket_update_alter_employee_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedTo', to='bugs.employee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to='bugs.employee'),
        ),
        migrations.AddField(
            model_name='update',
            name='madeBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugs.employee'),
        ),
        migrations.AddField(
            model_name='update',
            name='onTicket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugs.ticket'),
        ),
    ]
