# Generated by Django 4.0.3 on 2022-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_ticket_assignedto_ticket_createdby_update_madeby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Front End', 'Front End'), ('Back End', 'Back End')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='updateId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
